### ISSUE TITLE
How could I find the S2DTW code

### ISSUE THREAD

**Issue by sakura2233565548** [KoDohwan/Video-Text-Representation-Learning-via-Differentiable-Weak-Temporal-Alignment#4]
Hi, Thanks for your excellent work! I can not find the S2DTW core code, only find the soft_dtw in your released file. Could you share the S2DTW code with me? Thanks a lot!

**Comment by KoDohwan** [comment]
Hi, the code you want is already in the soft_dtw, this repository.
Line 351-375 of the soft_dtw is an implementation of S2DTW but the name is still the soft_dtw with negative_dot_product.
I'm sorry for the confusion.

**Comment by sakura2233565548** [comment]
> Hi, the code you want is already in the soft_dtw, this repository. Line 351-375 of the soft_dtw is an implementation of S2DTW but the name is still the soft_dtw with negative_dot_product. I'm sorry for the confusion.

Thanks a lot! I have found this code~
