### ISSUE TITLE
How can I find the apendix?

### ISSUE THREAD

**Issue by Xiaoxi-Luo-CL** [KoDohwan/Video-Text-Representation-Learning-via-Differentiable-Weak-Temporal-Alignment#6]
Hello! At the end of your paper, you said that "Future directions, limitations, and negative societal impacts are discussed in the appendix".I'm very interest in this part, but I can't find your appendix on Google. Would you please send me a copy of your appendix? Thanks a lot!

**Comment by KoDohwan** [comment]
Thanks for your interests in our work.

You can see the appendix at the official CVPR 2022 repository below:
https://openaccess.thecvf.com/content/CVPR2022/html/Ko_Video-Text_Representation_Learning_via_Differentiable_Weak_Temporal_Alignment_CVPR_2022_paper.html

**Comment by Xiaoxi-Luo-CL** [comment]
Thanks a lot! Have a nice day!
